GET http://localhost:3002/api/v1/

###

GET http://localhost:3002/api/v1/meetings
Content-Type: "application/json"
###

GET http://localhost:3002/api/v1/meetings/cola

###

POST http://localhost:3002/api/v1/meetings/addmeeting
Content-Type: application/json

{
    "meetingName": "cola"
}

###

POST http://localhost:3002/api/v1/meetings/addtopic
Content-Type: application/json

{
    "topicName": "money",
    "meetingName": "cola",
    "duration": 30
}

###

POST http://localhost:3002/api/v1/meetings/addtopic
Content-Type: application/json

{
    "topicName": "money2",
    "meetingName": "cola",
    "duration": 20
}

###

PUT http://localhost:3002/api/v1/meetings/updatetopic
Content-Type: application/json

{
    "topicName": "money",
    "isFinished": false,
    "meetingName": "cola",
    "duration": 40
}

###

PUT http://localhost:3002/api/v1/meetings/updatetopic
Content-Type: application/json

{
    "topicName": "money2",
    "isFinished": false,
    "meetingName": "cola",
    "duration": 100
}

###

GET http://localhost:3002/api/v1/meetings/cola/start

###

GET http://localhost:3002/api/v1/meetings/cola/finish